version: '3'

services:
    repository_buster:
      build: .
      restart: unless-stopped
      environment:
        REPOSITORY: buster
      volumes:
        - ./db:/opt/repository/db
        - ./incoming:/opt/repository/incoming
        - ./pool:/opt/repository/pool
        - ./www:/opt/repository/www

    repository_bullseye:
      build: .
      restart: unless-stopped
      environment:
        REPOSITORY: bullseye
      volumes:
        - ./db:/opt/repository/db
        - ./incoming:/opt/repository/incoming
        - ./pool:/opt/repository/pool
        - ./www:/opt/repository/www
